#!/usr/bin/perl -w

use strict;
use warnings;

print <<HTML;

<html>

<head>

<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>

</head>

<body bgcolor='#ffffb8' link='#a03830' vlink='#a03830' alink='#ff3830'>

<!-- http://phrogz.net/css/vertical-align/ -->
<table width='100%' height='100%'>
	<tr>
		<td style='vertical-align:middle'>
			<p align='center'><font size='4' face='SansSerif'>
			Input from STDIN <br>
			<a href='local://close/now'>Click here to close, press Esc or Enter </a>
			</font></p>
		</td>
	</tr>
</table>

</body>

</html>

HTML
